# Generated by Django 4.2.5 on 2023-09-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reguser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
