# Generated by Django 4.2.5 on 2023-09-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arta',
            options={'verbose_name_plural': 'Статьи'},
        ),
    ]
